### PR TITLE
Save Track JSON

### PR DESCRIPTION
**Pull request by AlmightyYakob**
Depends on #136.

This PR changes the saving of detection into girder by always saving as Track JSON. This also maintains backwards compatibility. This is because if the latest detection file in girder is a CSV, it will call the functions that were already in place, but if not, it will either simply return the contents of the file, or convert it to `track_json` first, and then return it.

To maintain the CSV format in some way, I've added an `export_detections` endpoint, which serializes the JSON format back into the CSV format we've been using. This was mainly done by moving code from the `save_detection` endpoint (which used to do exactly this) into this endpoint.

Now, there are two cases for retrieving detections:
* Track JSON, from a CSV file
* Track JSON, from a JSON file

To my knowledge, I've made the response consistent between CSV/JSON backend storage, but if you find something I've missed, please lmk.

### CODE REVIEW

**Comment by subdavis** [comment]
detection json is going to be removed soon, so I don't know how much sense it makes to merge code that stores data into detection json files, since we'd want to immediately transition to track json files.

This seems like it would cause a bit of extra headache to run migrations on. Would it make more sense to postpone this PR until after the client track work is done so that there are only 2 cases for retrieving and 1 for persisting?

**Comment by AlmightyYakob** [comment]
> detection json is going to be removed soon, so I don't know how much sense it makes to merge code that stores data into detection json files, since we'd want to immediately transition to track json files.
> 
> This seems like it would cause a bit of extra headache to run migrations on. Would it make more sense to postpone this PR until after the client track work is done so that there are only 2 cases for retrieving and 1 for persisting?

Sounds good to me :+1:

**Comment by AlmightyYakob** [comment]
I may still have to address the output of running pipelines.

**Comment by AlmightyYakob** [comment]
It seems like the pipelines output will work fine, as when retrieving detections the backend can still read in CSV, but I can't definitely test it because I don't have a GPU on my machine.

**Comment by subdavis** [comment]
FYI this branch has been integrated in #137 and can be closed

**Pull request closed without merging**
