### PR TITLE
Housekeeping/track centric

### PR DESCRIPTION
**Pull request by subdavis**

### CODE REVIEW

**Comment by BryonLewis** [comment]
Backlog of small tasks and items I want to fix for the track-centric version

- [ ] State management between 'edit' states.  [Playback, Selected, Editing, New Track, Head/Tail] 
- [ ] Errors regarding creating a new track and switching to head/tail annotation
- [ ] Left size TypeList header and Button need to be placed static and outside of the scroll box
- [ ] Fix Event Viewer scaling issue
- [ ] Prompting for deletion is not enabled
- [ ] Seeing if I can get annotations to update without updating the whole array of visible tracks
- [ ] Remove code to track Watcher updating in Layers.vue
- [ ] Determine if we want Bounds updating to happen inside of Layers or elsewhere.  (FeaturePointing has a use class for updating the Head/Tail Features, do we want something like that)
- [ ] Add Types for each of the formatted GeoJSON used in the AnnotationLayers

**Comment by subdavis** [comment]
I tested this pretty thoroughly

* There's still a problem with new track.  If you create a new track and draw a bounding box, then delete the track, you end up editing some other random track.
* the export feature now downloads JSON sometimes (if json is the most recent annotation type saved).  It should always export a CSV.

**Comment by BryonLewis** [comment]
> * There's still a problem with new track.  If you create a new track and draw a bounding box, then delete the track, you end up editing some other random track.

I'll take a look at it tomorrow.  I think it has to do with the new ability where you delete a track and it automatically selects another track.  There might be a delay in `editingTrack` changing to false which would cause the next selected track to be in edit mode instead.

**Comment by BryonLewis** [comment]
> I'll take a look at it tomorrow. I think it has to do with the new ability where you delete a track and it automatically selects another track. There might be a delay in `editingTrack` changing to false which would cause the next selected track to be in edit mode instead.

Yup this is the case, when you delete something it selects the 'next' element before deletion.  This selection is manually sets the `selectedTrackId.value` which means it will maintain the current `editingTrack` state.  Adding a new track is a form of editingTrack.  We could either make it so it doesn't automatically select anything, or so that it will cancel editing right after it moves to the next track.

**Comment by subdavis** [comment]
@BryonLewis I still need to take care of exporting CSV instead of json.  Hope I can do that this afternoon.

**Comment by AlmightyYakob** [comment]
> * the export feature now downloads JSON sometimes (if json is the most recent annotation type saved).  It should always export a CSV.

I'm curious under what conditions you observed this behavior, as I've tested this with both JSON and CSV as the most recently saved annotations, with CSV being exported both times.

**Pull request merged**
