### PR TITLE
Enable pinch zoom on mobile

### PR DESCRIPTION
**Pull request by zachmullen**

### CODE REVIEW

**Comment by subdavis** [comment]
I just noticed the line above, there are several mistakes:

```
        {
          action: 'geo_action_select',
          input: { right: true },
          name: 'button edit',
          owner: 'geo.MapIteractor',
        },
```

* correct action is `geo_action.select`  (`.`, not `_`)
* owner is misspelled.

What is the impact of these?

**Comment by zachmullen** [comment]
🤷

**Comment by BryonLewis** [comment]
> What is the impact of these?

`geo_action_select` is the same as `geo_action.select` - we should probably update it
https://github.com/OpenGeoscience/geojs/blob/fe0b1399af1787f1d038be460bfa5ea0d2f1e67a/src/action.js#L13
The owner is a reference that can be used when intercepting actions.  Doesn't really affect us at the moment but should be updated.

**Comment by zachmullen** [comment]
@BryonLewis are you wanting me to try to also make those changes? I feel like that is probably better on a separate PR

**Comment by BryonLewis** [comment]
> @BryonLewis are you wanting me to try to also make those changes? I feel like that is probably better on a separate PR

I'm making a note of those items to be in a different PR.  I haven't had time yet to pull and do testing of this PR, but will be able to later.

**Review by subdavis — APPROVED** [review]

**Review by subdavis — CHANGES_REQUESTED** [review]
approved by accident.  I haven't been able to test this yet, sorry

**Review by BryonLewis — APPROVED** [review]
Pulled and tested on laptop and no adverse effects with zooming/panning or selecting and moving edit handles.

Tested on a Lenovo Duet Chromebook (both touchscreen and mouse).  Seems to work well.  I actually enjoy the zooming using touch more than the mouse.  Selection works, but things like selecting edit handles and moving them don't work with touch but will work with mouse.  It doesn't appear like having touch enabled will adversely impact anything either.

Observations:
- No effect on mouse controls when system doesn't have touch controls
- Selection using touch works for tracks
- Touch and mouse controls can exist side by side
- Editing of boxes requires mouse controls
- Would need to modify logic to enable editing using touch controls (Not a now worry)

**Review by subdavis — APPROVED** [review]

**Pull request merged**
