### PR TITLE
Cancel Jobs

### LINKED ISSUE #457: [BUG] Implement job cancellation
**Describe the bug**
 Jobs that get cancelled are stuck in the list forever.

**To Reproduce**
Cancel a job.

### PR DESCRIPTION
**Pull request by subdavis**
fixes #457

### CODE REVIEW

**Review by BryonLewis — APPROVED** [review]
Once I got a version working through the pull/build process this worked properly through the different modes.  Tested with video conversion, pipelines and training.  I'm assuming eventually we want to allow a user to cancel their own jobs.

The only thing I noticed is that the jobs indicator (spinning icon in the toolbar) doesn't properly update if a user cancels the job on another tab, or if an admin cancels the jobs.  It's a very specific circumstance that would cause this.  It's a tiny 2 line change, and I have a branch, I don't know if you wanted 'client' stuff polluting this PR or if you want it as a separate PR afterwards?  I'm good with either way (doing a PR into this PR, or updating it afterwards as separate PR) just let me know.

**Comment by subdavis** [comment]
@BryonLewis go ahead and add your changes, I think I'd prefer them here.

**Comment by subdavis** [comment]
Thanks!

**Comment by subdavis** [comment]
@BryonLewis pls re-review srry.

**Review by BryonLewis — APPROVED** [review]
Sorry about the delay.

**Comment by subdavis** [comment]
NP, I'm being needy.

**Pull request merged**
