### PR TITLE
[feature] allow independent head and tail track annotations

### LINKED ISSUE #10: Bug: placing head or tail point while a track is in edit mode enters invalid state
* right click a track to enter edit mode
* press f
* click anywhere until a large dot appears.

Screenshot from 2020-03-19 09-57-23

You end up with something that looks like a new track but is different than all the others and as far as I can tell is not supposed to be there.  You can drag the dot once to turn it into a box:

Screenshot from 2020-03-19 10-00-22

### PR DESCRIPTION
**Pull request by subdavis**
Adds ability to annotation head and tail independently

* removes `f` and `d` keybindings for annotation
* adds `g` and `h` keybindings for head annotation (right and left handed)
* adds `t` and `y` keybindings for tail annotation (...)
* adds `f` and `d` keybindings for +1 frame and -1 frame (standard video interface UI/UX)
* adds `q` for delete head/tail annotations.

Press g, h, t, or y to start an annotation.  
* if neither exists, you will be prompted to provide both, starting with the key you pressed.
* if you don't want to provide both, tap any of the keys to exit the edit state.
* if both (or one) already exists, you will only be prompted to provide the one corresponding to the key you pressed

PR also cleans up some `console.log` lines and adds comments denoting code quality issues.
Adding line will be done in a follow-up PR.

fixes #10

### CODE REVIEW

**Comment by subdavis** [comment]
@BryonLewis Good catch.  I added `q` for delete, but forgot to update that menu.

**Comment by BryonLewis** [comment]
This is just a general UI comment which I'm sure will have further discussions in the future.  Should there be a UI element indicating the tool you're currently using.  Some indication that the cursor is in head picking mode vs tail picking mode.  Sometimes in the bottom left corner on applications there is some text indicating what the program believes you are doing currently.  IE: "select the head of the detection..." then switches to select tail.  I believe the initial old version of CAD did stuff like that (like DOS running CAD).

**Comment by subdavis** [comment]
Definitely, there should be.  I'm not planning to invest in heavy UX improvements until we have a clearer understanding on our path forward with this app, but I'm willing to be challenged on that.

There should also be in-app explanations of all the controls.

**Comment by subdavis** [comment]
@BryonLewis updated menu dropdown, ptal.

**Pull request merged**
