### PR TITLE
Add linting and import sort to CI

### PR DESCRIPTION
**Pull request by subdavis**
Prevent merge if linting and import sorting aren't done.

This also cleans up missed linter and sorter issues, so it might have to wait for other server PRs to merge to avoid conflicts.

### CODE REVIEW

**Comment by subdavis** [comment]
Lint failing on the server but passing locally.  I don't know what's going on.

**Comment by subdavis** [comment]
Black upgraded to v20 and apparently has some new rules.  https://github.com/psf/black/blob/master/CHANGES.md#208b0

Note that you'll need to reinstall dev-requirements.txt to get the fresh version.

**Comment by AlmightyYakob** [comment]
Instead of directly using `black` and `isort`, I'd prefer if we were to use flake8 for linting, and add plugins that suit our needs, which would include [flake8-black](https://pypi.org/project/flake8-black/) and [flake8-isort](https://pypi.org/project/flake8-isort/). This would also allow us to add any number of plugins that we like. What do you think?

**Comment by subdavis** [comment]
I'm not really familiar with flake8 and what value it provides.  I like black and isort because they're pretty trivial to run and configure, but I'm open to something else if it's a D&A standard.

I've probably already spent more time this morning figuring this out than I should have, but if you'd like to add to this PR you're welcome to do so.

I don't really like that `flake8` doesn't support pyproject.toml because it's my understanding that pyproject.toml has sort of been blessed as the standard configuration method python, but this may not be a big deal.  I like that pyproject.toml config is picked up in my virtual env no matter what subfolder I'm in.  

This PR doesn't include any sort of precommit hook, which I'd also like to have, but I was too lazy.

**Comment by AlmightyYakob** [comment]
> I'm not really familiar with flake8 and what value it provides. I like black and isort because they're pretty trivial to run and configure, but I'm open to something else if it's a D&A standard.

I've always seen it used when doing linting on a project, and it provides a really nice plugin system for linting.

> I don't really like that `flake8` doesn't support pyproject.toml because it's my understanding that pyproject.toml has sort of been blessed as the standard configuration method python, but this may not be a big deal. I like that pyproject.toml config is picked up in my virtual env no matter what subfolder I'm in.

The entire python community and myself agree that flake8 should support `pyproject.toml`, yet it's still missing. However I think you can still specify configs in `pyproject.toml` for tools that are used through flake8, like `black` and `isort`. If that's correct then the current config we have could remain unchanged. I can look into this.

> This PR doesn't include any sort of precommit hook, which I'd also like to have, but I was too lazy.

We've done this on [multinet](https://github.com/multinet-app/multinet-server), so I could add this if it's desired.

**Comment by subdavis** [comment]
@AlmightyYakob this is blocking server work.  Can we merge this and follow up with flake8 later?

**Review by AlmightyYakob — DISMISSED** [review]

**Comment by subdavis** [comment]
@AlmightyYakob had to rebase, could you approve again? thanks.

**Pull request merged**
