### PR TITLE
Use provide.handler instead of emit

### PR DESCRIPTION
**Pull request by subdavis**
This is the logical sibling of my provides PR to circumvent the type loss happening in emitters.

This has a certain elegance to it: the ability to globally use a collection of state and handlers without having to prescribe a specific implementation like Vuex requires.

Downstream retains full control such that it can maintain additional state and modify behaviors based on that hidden state, but the interface is fixed (which it was all along, there just wasn't a formalization).

I haven't tested this too thoroughly, but I'm happy with the style.

I'm considering implementing a sort of dummy handler for use cases like Jake where only parts will be used.  Basically an abstract base class.

### CODE REVIEW

**Comment by subdavis** [comment]
@BryonLewis I don't want you to spend time making sure this works, I just your thoughts on the goal.  I haven't put in the work to test thoroughly myself yet.

**Comment by BryonLewis** [comment]
Going down this path, I would assume that next the Layers themselves would have no more need to use `this.bus` inside of the drawing layers.  

Benefits:

- True type checking for events emitted up to the use_whatever composition functions
- No longer need to have the overhead of extending or including Vue just for emitting events in items that donb't necessarily use any vue features (no computed, no watchers).
- Removes a bunch of passthrough handlers of emit signals, like in sideBar

Disadvantages:

- The vue dev tools I'm guessing won't pick up these events when they occur so debugging is now more manual.  So now to figure out what is selecting the track I would have to debug the trackList, the eventViewer the RectangleLayer and the PolygonLayer instead of looking at the dev tools for the emitted signal.
- The 'blueprint' system of a vue component is gone.  I typically look at a component for the inputs/outputs/functionality.  While the component view didn't give an all encompassing view of inputs/outputs (like in the case of provide annotator) it did give a fairly decent quick starting point.  I did notice that in LayerManager.vue you incorporated the entire `useHandler` whereas in SideBar.vue you destructured to only the handlers you wanted to use.  I would suggest destructuring using names making it clear that these are more like event functions which may have side effects that influence the properties that are imported.  It gets into that same thing as mapGetters/mapState where there is an extra lookup to understand where this function originates. `this.$emit` just being there added some context as to what the function was doing.
- The same as before where it does limit portability of components, not that we really had a need for that anyways.

This is the obvious next step in the system if we really want to implement Typescript to it's highest.  My other worry which I don't know if it is valid is that this may bring a higher learning curve to on-boarding someone into the project.  I'm assuming you will write some documentation for this just like you did for `provides` and that will help.

**Comment by subdavis** [comment]
I think in between your current outstanding small PRs and the start of the work on attributes, we should merge this.

I agree with the assessment above.  There are things we can do to add some instrumentation back in, but that's the biggest drawback here.  I thought the blueprint was misleading: it made it look like components were using things they were actually just passing through, so this is an upgrade to me: You can search for `removeTrack` and find only the exact places it's being used.  Portability ship sailed in the last PR.

We're going to need to add some observability for a help system, so we can probably hook in an emit debugger based on `process.env.NODE_ENV` or something, IDK.

**Comment by BryonLewis** [comment]
was the intention for this to continue down into the LayerManager items (Poly/Rect others) to remove the emit from them or to start with the current state of this PR as a base and get it merged in?

**Comment by subdavis** [comment]
I'm not sure.   I'm tempted to start with this and expand later, but if you think we should do it all here, that's cool too.  No strong opinion.

**Comment by BryonLewis** [comment]
I'm fine with doing it piecemeal as long as eventually we attempt to maintain consistency.

**Review by BryonLewis — APPROVED** [review]
Pulled and did some testing.  All seems to work properly.

**Pull request merged**
