### PR TITLE
Lint templates with vue-type-check

### PR DESCRIPTION
**Pull request by subdavis**
use https://github.com/Yuyz0112/vue-type-check  for template linting in `src/`

If we like this idea, I'll expand it to other source code, but `src/` is currently the most critical.

### CODE REVIEW

**Comment by BryonLewis** [comment]
This is awesome to have.  Should it be added  as part of the lint script instead of just having a reference that it is occurring happening during the actions?

**Comment by subdavis** [comment]
@BryonLewis that's a good question.  I don't know how to make it all run on `yarn lint` but I could add `yarn lint:templates` that runs this script.

**Review by BryonLewis — APPROVED** [review]
Looks Good.

**Comment by subdavis** [comment]
This will need to merge again after master is fixed.

**Pull request merged**
