### PR TITLE
Continue if build failed, send failure report

### LINKED ISSUE #231: Send emails on failed deploy

### PR DESCRIPTION
**Pull request by AlmightyYakob**
Fixes #231 

This updates the behavior of the builds to start the service independent of building, so that if it fails, the service can come back online without issue. Furthermore, if the build fails, it will send a failure report to the email address we specify.

### CODE REVIEW

**Comment by AlmightyYakob** [comment]
I've tested this on the server, and the mail sending works without issue.

**Comment by AlmightyYakob** [comment]
> This is CI config, so I'm just going to trust that it works.
> 
> Is there a reason you used a vars file rather than just entering the variable into CircleCI env config?

This runs on the viame server, not in CI.

**Comment by subdavis** [comment]
Oh, I see.  Could you specify where to put `vars.yml` in the README?  Is it in the project root or inside `docker/ansible`?

**Comment by AlmightyYakob** [comment]
> Oh, I see. Could you specify where to put vars.yml in the README? Is it in the project root or inside docker/ansible?
> 
> Better yet, could you place a .vars.example.yml in the place where it's supposed to go with the correct schema and dummy values?

Good idea, I'll do that.

**Pull request merged**
