### PR TITLE
Change display inside VIAME folder

### LINKED ISSUE #226: Resolve ambiguities in file selection in front end and not being able to download individual files
Maybe the easiest way is to just be able to download checked individual files short-term? It's weird that you can view single .json and images but not download or interact with them. They should probably either be hidden or allow the user to download individual images/files (there might also be a use case for the later).

### PR DESCRIPTION
**Pull request by subdavis**
Inside a VIAME folder (marked for annotation) 

* disable selection of rows.
* Show "download" and "run pipeline" buttons, same as if we were in the parent folder and had selected this folder.

This should make it more clear that there's something "special" about this folder.

Screenshot from 2020-07-31 15-07-34

fixes #226

### CODE REVIEW

**Comment by subdavis** [comment]
Yeah that doesn't work, you're right.

I'm actually starting to think that this whole file system abstraction for ViAME web is useless and confusing for users, and a flat, searchable list of datasets would be better.

That would certainly make it easier to limit our dependency on girder-specific features.

I might float this idea to the team tomorrow...

Thanks for the feedback.

**Comment by subdavis** [comment]
Did you have a specific suggestion regarding what should happen about auxiliary folder?  The only thing the client has enough information to do, I think, is block access to that folder.  Once inside, additional API calls would be necessary to figure out the identity of the parent, and I don't want to use any more Girder calls than absolutely necessary.

If you have another idea, LMK.

**Comment by BryonLewis** [comment]
> Did you have a specific suggestion regarding what should happen about auxiliary folder? The only thing the client has enough information to do, I think, is block access to that folder. Once inside, additional API calls would be necessary to figure out the identity of the parent, and I don't want to use any more Girder calls than absolutely necessary.
> 
> If you have another idea, LMK.

I really don't know what the best case scenario is depending on the use case.  I **think** the main thing is that people **might** want to export their data and **most likely** detection in a  VIAME CSV or other format.  The auxiliary JSON history files probably don't mean much to them.  I hate taking control away, but do we just don't allow them to browse into the annotation folder?  This may be a conversation with Matt to clarify exactly what is needed.

**Comment by subdavis** [comment]
Less is more, in this case, I think.  Let's just disable navigation to auxiliary for now.  Nothing in there but empty promises and broken dreams.

Would be fairly easy to show a nice "history" view somewhere that people could explore old versions of annotations.  I also have an itch to fix save so that it only sends the parts that changed rather than the entire annotation file every time.  These are topics for another day

**Comment by subdavis** [comment]
Disabled Auxiliary folder.

**Pull request merged**
