### PR TITLE
Client/type sharing

### PR DESCRIPTION
**Pull request by BryonLewis**
Started the interface required to eventually implement the Type Sharing which will evolve into track/detection attribute sharing

Added a settings section to the typeList in the similar style as the trackList settings.  These settings are stored within localStorage just like the newTrackSettings and uses the same code in useSettings to do so.

Structure Changes:
We now have two separate list of types that are managed.  We have `allTypes` like before that includes all types that are referenced in the system including any new types created by the user.  We also now have `defaultTypes` which are loaded from the metadata and added to using the Import option.  `allTypes` is now a computed property which uses `visibleTypes` (the previous all types) appended with the `defaultTypes` 

Updates that I made are attempted to be made using props that have a default of 'off' to prevent them effecting any library releases of the code.  IE - `lockTypes` belongs to the viame-web-common area but is needed inside of the trackItem so it is included as a prop with a default of false.  I don't know how sustainable this style is and am open to any other suggestions.   So while there are props on the items, they are defaulted to an off type and hopefully with the new template linting of types that helps any of the issues that might occur.

These new settings include three main options:
- Import Types - Ability to provide a list of types to import as a template to be used for the types in the system.  The list is newline separated and includes a note that UnUsed types needs to be turned on to see them.
- View Unused - May change the name of this.  This is turned on to see all of the types in the type list including items that aren't being currently used by any tracks.
- Lock Types - Makes it so the user can only use types that are in the existing AllTypes list.  Prevents the user from entering in custom types in the trackList section.

Locking Types:  While locking the types it makes it so that there is a lock icon next to the type and if the user attempts to empty an alternative type it reverts back, highlights the lock and displays a tooltip indicating that the user should only pick a type from the list.

TypeListDemo

I'm a little torn on if the "Import+" should be inside the settings or near the delete/settings icons like it is in the tracklist area?

Maybe we want to get some feedback before mergning to see if this is on the right track for allowing sharing of types across datasets.

### CODE REVIEW

**Comment by subdavis** [comment]
Looking forward to reviewing this.

**Review by subdavis — CHANGES_REQUESTED** [review]
Code here is great, no real suggestions for improvement.

UX-wise, also mostly good.  I have a few specific concerns

1. Import types should probably be `Add types` or something.  Import is a little misleading.
2. When you import types and leave an empty newline, it imports as the empty string.  This should be filtered out.
3. I don't like how the lock icons and tooltips are used to show error conditions.  The `type=text` inputs were used to avoid the rendering cost of the type list for every track item, which could get expensive while scroling, by moving the option list up into TrackList.  However, I think a `<select>` would be a lot more appropriate than doing onBlur enforcement.  Could we try switching to a `<select>` if lock is enabled and just not allowing any sort of text input?  

For #3, I can take a swing at that if you're busy with other stuff. It may perform badly, IDK.

I actually also feel like the line between localstorage and server save is getting blurred.  markChangesPending is being used in a lot of places.  The disconnect between the call to that method and the call to `getTypeStyles(allTypes)` really threw me off (even though it's my own fault for writing it like that.  I'm going to think about how to make this more clear.  No action needed here.

**Comment by BryonLewis** [comment]
> 3. I don't like how the lock icons and tooltips are used to show error conditions.  The `type=text` inputs were used to avoid the rendering cost of the type list for every track item, which could get expensive while scroling, by moving the option list up into TrackList.  However, I think a `<select>` would be a lot more appropriate than doing onBlur enforcement.  Could we try switching to a `<select>` if lock is enabled and just not allowing any sort of text input?
> 
> For #3, I can take a swing at that if you're busy with other stuff. It may perform badly, IDK.

That's exactly why I kept with the datalist, I figured that you implemented that to avoid creating all the types for each track in the list.  I was looking through MDN trying to find anything that would disable text/tytping and only  dropdown inputs on a datalist but couldn't anything.  I mean technically it should only be 8-20 track items visible at once although you could have hundreds of types.  I'll take a look at it and do some performance testing to see what can be done.

> 2.  When you import types and leave an empty newline, it imports as the empty string. This should be filtered out.

my brain is broken, don't know how I missed that.

**Comment by BryonLewis** [comment]
@subdavis - I added in the select option and updated the review comments.  The stuff with the focus and blur is used to maintain some consistency between the <input datalist> and the <select> option with the keyboard commands.  So the shift+enter and clicking enter after should behave properly, as well as the down key.  I could use the same HTMLElement reference because only one of them is rendered at a time.

**Review by subdavis — APPROVED** [review]
I just noticed another problem with manually added types:

If you create a type using the `+types` button, then set a track to have that type, then change it, the type gets deleted as if it were one of the ephemeral types.  There needs to be some distinction between explicitly added and ephemeral types.

Can address this is another PR if you want: maybe open an issue for it?  That's the only issue here.

**Comment by subdavis** [comment]
BTW, the change to `<select>` is really nice I think that was a good choice.  I like not having the tooltip on the lock button too: it was distracting.

**Comment by BryonLewis** [comment]
> I just noticed another problem with manually added types:
> 
> If you create a type using the `+types` button, then set a track to have that type, then change it, the type gets deleted as if it were one of the ephemeral types. There needs to be some distinction between explicitly added and ephemeral types.

Are you sure that is the case and it just isn't hidden as an unused type?  You need to have the setting on to see unused types.  Once it is removed it becomes an 'unchecked' type with no annotations so it isn't visible by default.  I didn't have to have a huge list of empty/unused types displayed so that is why I made it a setting.  As soon as an item is assigned to an unsused type it is made visible.  This is the same behavior as before where if no annotations of a type existed it would be removed from the list.

>I think you probably need a new metadata section in the API that isn't the style section to keep these custom added types in.

I need to do some thinking about it.  There may be a benefit in keeping the type list separate from the styling but half of me believes that you want styling to be the same across different datasets with the same type names.   So your "blue fish" type is always blue in color.  The way it is now, the new type always saves with it the styling.  Without connecting the styling to the types, the styling is generated randomly using the d3.ordinal naming function so you could have disparate styles for the same shared types.  I'll most likely be working on the attributes editor and section next and I'll need to expand/change the metadata accordingly so I'll look into this closer.

**Comment by subdavis** [comment]
> Are you sure that is the case and it just isn't hidden as an unused type? You need to have the setting on to see unused types.

I forgot about that, sorry.   Everything is working as expected.

**Comment by BryonLewis** [comment]
image
If I was going in there to do some changes, decided to update the mode settings as well.

**Review by subdavis — APPROVED** [review]

**Pull request merged**
